### PR TITLE
Improved KD fitting

### PR DESCRIPTION
**Pull request by wsdewitt**
This PR introduces a prototype for an improved $K_D$ estimation method. It is currently in the form of a notebook and CSV output in the subdirectory [`tite-seq-modeling/`](https://github.com/jbloomlab/Ab-CGGnaive_DMS/tree/improved-Kd-fitting/tite-seq-modeling), and **should be ported to a full-fledged pipeline component before merging**.

The key improvements/changes are summarized below. For full details, read through the new notebook.

### 1. From barcode-wise to variant-wise estimates

The current $K_D$ fitting procedure (fitting the "mean bin" curve to a Hill function) fits a $K_D$ for each barcode, from which a given variant $K_D$ is computed as the mean of the barcode-wise $K_D$ estimates for all barcodes assigned to the variant. This is statistically underpowered because it requires us to estimate many $K_D$ parameters for a variant when we eventually want just a single $K_D$ inference, and the barcode mean bin curves can be quite noisy. Here, we instead aggregate reads at the variant level and infer variant-wise $K_D$ from the complete data. This is illustrated for one variant in the figure below, where barcode-wise curves (light grey) are messy, but the aggregated curve (black dots) is not.

image

### 2. Binning and biophysical scaling

The experiment uses log-spaced fluorescence bins, and the current $K_D$ method fits a Hill function to mean bin curves as a proxy for fluorescence. However, the biophysical picture is that fluorescence is proportional to fluorophore occupancy which goes as a Hill function. So, due to the log-spaced bins, we should be using $\log(\mathrm{hill}(x))$, not $\mathrm{hill}(x)$ (mean bin curves are a proxy for log-fluorescence). This discrepancy results in systematic scaling issues in the current $K_D$ estimates. One way to illustrate this issue is by looking at the fluorescence data. The first row of the figure below shows the log-fluorescence titration for both libraries, and it looks like the half-max matches our WT estimate of $\log K_D\simeq -10.4$, and mismatches the measurement from BLI, shown in red. But the y-axis here is log-fluoresence, so we shouldn't be looking at the half-max on this scale: log transforming fluorescence distorts the half-max because it expands the low values in the plot. The second row of panels shows the same data without the log transform, and this is a closer match to the BLI data (although not saturating as clearly).

image
image

### 3. Likelihood-based modeling

We replace the mean-bin heuristic with a full likelihood-based model for the data-generating process. The general idea is to model the read count matrix (bins by concentrations). For example, the matrix for WT looks like this:

output data

Our model is detailed in the subsequent subsections, and results in a predicted read count matrix:

output

#### Latent fluorescence

We sort cells at 9 concentrations $x_1, \ldots, x_9$. For a cell of variant $i$, model the fluorescence $z_i$ at each concentration $x_j$ with a log-normal distribution:

$$
\log z_i\mid x_j \sim \mathcal{N}\left(\log f(x_i; \kappa_i, \alpha_i), \ σ^2\right),
$$

with median given by a linear function of antigen occupancy of the cell, which obeys Hill-Langmuir kinetics.

$$
f(x_j; \alpha_i, \beta, \kappa_i) = \alpha_i\left(\frac{x_j}{x_j + \kappa_i}\right) + \beta,
$$

where $\kappa_i$ is the dissociation constant ($K_D$) of variant $i$, $\alpha_i$ models the maximum fluorescence at saturation of variant $i$ (a function of the variant's surface expression of antibody), $\beta$ models a cell autofluorescence baseline, and $\sigma^2$ is the variance profile on the log-fluorescence scale.

#### Fluorescence bins

We sort cells into 4 fluorescence bins, defined by the right-open intervals bounded by $b_0=0 < b_1 < b_2 < b_3 < b_4=\infty$. The probability that a cell from variant $i$ sorted at concentration $x_j$ appears within a fluorescence bin defined by the interval $[b_{k-1}, b_k)$ is obtained by integrating the log-normal distribution over the bin interval:

$$
p_{ijk}(\alpha_i, \beta, \kappa_i, \sigma) = \Phi\left(\frac{\log b_k - \log f(x_j; \kappa_i, \alpha_i)}{\sigma}\right) - \Phi\left(\frac{\log b_{k-1} - \log f(x_j; \alpha_i, \beta, \kappa_i)}{\sigma}\right),
$$

where $\Phi$ is the CDF of the standard normal distribution.

#### Compound counting process for cells and reads

Let parameter $\rho_i$ denote the library fraction of variant $i$. We know the total number of cells $C_{jk}$ sorted at concentration $x_j$ and fluorescence bin $k$, so (by the Poissonization theorem) the number of cells of variant $i$ sorted at concentration $x_j$ and fluorescence bin $k$ is a random variable $C_{ijk}\sim\mathrm{Pois}(C_{jk} \rho_i p_{ijk})$. 

We additionally know the total number of reads $R_{jk}$ sequenced from cells sorted at concentration $x_j$ and fluorescence bin $k$. Conditioning on the number of cells $C_{ijk}$, the number of reads of variant $i$ sequenced from cells sorted at concentration $x_j$ and fluorescence bin $k$ is a random variable $Y_{ijk}\mid C_{ijk} \sim \mathrm{Pois}(R_{jk} C_{ijk})$. The unconditional $Y_{ijk}$ is a compound Poisson random variable:

$$
Y_{ijk} = \sum_{\ell=1}^{C_{ijk}} Q_{ijk}^{(\ell)},
$$

where $Q_{ijk}^{(\ell)}\sim\mathrm{Pois}\left(\frac{R_{jk}}{C_{jk}}\right)$ is the number of reads from cell $\ell$ of variant $i$ sorted at concentration $x_j$ and fluorescence bin $k$.

The PMF for $Y_{ijk}$ is intractable, but we expect it will look like an over-dispersed Poisson distribution. This motivates an approximation of $Y_{ijk}$ as a negative binomial random variable, with moments matched to the compound Poisson random variable, which are tractable. Denote the Poisson intensity of cells of variant $i$ sorted at concentration $x_j$ and fluorescence bin $k$ as

$$
\lambda_{ijk}(\alpha_i, \beta, \kappa_i, \sigma) := C_{jk} \rho_i p_{ijk}(\alpha_i, \beta, \kappa_i, \sigma),
$$

and the Poisson intensity of reads per cell (read depth) at concentration $x_j$ and fluorescence bin $k$ as

$$
D_{jk} := \frac{R_{jk}}{C_{jk}}.
$$

After some calculation for the moments, we find the approximation

$$
Y_{ijk} \sim \mathrm{NB}\left(\lambda_{ijk}(\alpha_i, \beta, \kappa_i, \sigma), \frac{D_{jk}}{D_{jk} + 1}\right).
$$

#### Likelihood

Finally, the log-likelihood given read count data tensor $Y\in\mathbb{N}^{n\times 9\times 4}$ is

$$
\log \mathcal{L}(\boldsymbol\alpha, \beta, \boldsymbol\kappa, \sigma; Y) = \sum_{i=1}^n \sum_{j=1}^9 \sum_{k=1}^4 \left(\log\gamma(\lambda_{ijk}(\alpha_i, \beta, \kappa_i, \sigma) + Y_{ijk}) - \log\gamma(\lambda_{ijk}(\alpha_i, \beta, \kappa_i, \sigma)) + \lambda_{ijk}(\alpha_i, \beta, \kappa_i, \sigma) \log\left(\frac{D_{jk}}{D_{jk} + 1}\right)\right),
$$

where $\gamma$ denotes the gamma function.

### 4. Constrained optimization

Whereas Adams et al. use a 0th order optimization (grid search), we use a scalable 1st  order method. The challenge with gradient-based MLE here is that we must constrain the parameters to ensure that the predicted library-level fluorescence matches the empirical FACS data, shown in histograms below.
Untitled

We use the [augmented Lagrangian method](https://en.wikipedia.org/wiki/Augmented_Lagrangian_method) with a generalized Kullback-Leibler divergence constraint on the library fluorescence distribution. This results in a sequence of MLE optimization problems with increasing constraint penalties, each of which we solve with L-BFGS-B.

## Results

To validate, we fit each of two libraries independently, which correlate well:
Untitled

We then take the mean $K_D$ from the two libraries for each variant (**todo:** joint estimate after confirming libraries correlate) and compare to the current $K_D$ method:
Untitled

### CODE REVIEW

**Comment by jgallowa07** [comment]
I'm helping assist in the integration of this method into the pipeline. After discussion with @wsdewitt , here is our current set of goals:

**goal one** (minimal viable product - for this PR)
- [ ] A run through / familiarize myself with the the pipeline and wills notebook notebook (define inputs).
- [ ] implement A new snakemake rule for barcode aggregation
- [ ] new rule for new delta binding affinity modeling code as seen in Wills notebook
- [ ] Fitting new outputs correctly into the documentation that gets generated

**goal two** (not strictly necessary, but expression is in the replay paper)
- [ ] Get expression notebook (existing R code) to run with the aggregated output from #2 above

**goal three** (more optional, if time allows)
- [ ] Modify polyspecificity in the same way.
- [ ] Get the Tugg data do do the same stuff as above. 

This is mostly for my own organization -- I'm still familiarizing and will be playing with this branch but any suggestions, considerations, and thoughts are welcomed!

**Comment by jgallowa07** [comment]
Getting close - hoping to have a working MWP by EOW. Based off of the discussions with @wsdewitt and @matsen our new dag now looks like:
dag

**Comment by jgallowa07** [comment]
The pipeline currently has quite the spattering of barcode-and-variant-level filters throughout it's steps. It's a little complicated to tell which ones are valid (lot's of hard coding for the filters being set), and whether or not they're in the correct place wrt this refactor.

Currently in the topic branch (plus un-pushed local changes I'm working through), these are the qc filters I've identified:

1. in prep_Titeseq_barcodes (which now also preps the SortSeq data for expression -- and needs to be renamed), we (a) Filter out the barcodes related to synonymous w/ silent mutation variants and (b) "We filter missing concentrations for each barcode in the barcode data, and for each variant in the variant data. Missing means the sum of reads is zero."
2. in Titeseq_modeling we (a) filter out variants with read counts <= 100
3. in collapse_scores, @tylernstarr : (a) filters out variants that contain less than 3 barcodes, and (b) filters out variants which do not appear in both libraries

Some questions that I'm considering and could use help with are (cc @wsdewitt ):

1. Should filter 2a be applied in the prep_Titeseq_barcodes step instead so that the sortseq data for expression calculation also has this filter applied before being executed?
2. Unfortunately, the Titeseq_modeling, and expression steps do not keep the barcode information around (as they stand, currently). So, if wanted to leave filter 3a as it stands I'd have to add the variant barcode support information to the outputs of those steps. The other option is to also bring these filters to the prep_Titeseq_barcodes step. I imagine the latter option is the cleaner approach, but could have downstream effects on the expression and binding fits?

**Comment by wsdewitt** [comment]
My suggestion is to forget about barcodes after the barcode aggregation step, and only apply variant-level filters.
- Filter **2a** is about reads and filter **3a** is about cells, so I'm fine with keeping these distinct, but variant-level
- For **3a (calculate expression)**, if there are, say, mean 10 barcodes per variant, we might want to raise the threshold from 10 cells (at the barcode level) to 10x10=100 cells (for the variant level).
- For **4 (collapse scores)**, there's no need for 4a, since we no longer have barcode-level inferences. I think it still makes sense to filter for variants measured in both libraries.

**Comment by jgallowa07** [comment]
Awesome, thanks, @wsdewitt 

> For 4 (collapse scores), there's no need for **4a**, since we no longer have barcode-level inferences. I think it still makes sense to filter for variants measured in both libraries.

Awesome, I was able to actually propagate the number of barcodes that were collapsed for each variant, through binding and expression, such that that information is available in the collapse step. In that case, should we keep **4a**? AFAIU, we would still have more confidence in values fit to variants with n barcode supports.

**Comment by wsdewitt** [comment]
@jgallowa07 Sure, if it's easy now, that's good.

**Comment by jgallowa07** [comment]
@wsdewitt This is now ready for you-review before (I assume) we'll have @tylernstarr take a closer look?

I would suggest:

- starting at the [summary page](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/results/summary/summary.md), and working your way through the steps, and peeking at the key files with your own sanity checks. 
- The [README](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/README.md) has been updated if you want to try out running the pipeline yourself (which would be helpful).

Once this is "approved", I'll happily remove the prototype notebooks, squash, merge, and finally re-run the replay pipeline!

## Comparison of final_variant_scores.csv

I did a comparative analysis of 1) the `main` branch final variant scores 2) Will's prototype final variant scores, and 3) the final variants scores that can be reproduced on this branch, as it stands. The full analysis notebook can be [found here]() and will be removed along with the rest of the [tite-seq-modeling/](tite-seq-modeling/) directory when we're ready to merge this. To summarize what I found in the comparison:

1. The new pipeline refactor still outputs all the same information as it did before about variants.
3. Less relevant to the comparison, but I found there was a (seemingly) non-trivial bug in @tylernstarr 's [collapse scores notebook](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/b81c92e798d66d840318ce6687e01bd0226557ab/collapse_scores.Rmd#L285). I assume we wanted to mask the phenotypes of all variants which had been observed in less than 2 libraries, OR had less than 3 barcode supports. Instead only variants that mated both these criteria were masked ... I have fixed that in this branch, which masks 32 variants that previously reported phenotype values. If I'm mistaken here, please let me know.
4. There's some sort of bug with how we're recording the link mutations in the final variants table. For example, there's only 13 wildtype linker sites reported, and there should be 15 according to the site map. I really do not see any benefit to keeping these in the final variant table. The only entries with phenotype values are wildtype ... the rest just have lot's of missing data, confusing IMGT mutations, and cause the table to have a weird number of entries when sanity checking. See the notebook for more.
5. The binding Kd's from Will's prototype, and this pipeline are very similar, with a max delta of 0.3. That gives me confidence that nothing much will change when we use these scores in the main replay pipeline. The expression scores changed, as to be expected, but seem correlate well with the previous scores (0.99) See the screenshot, or the notebook for more -- but note that no suffix behind the phenotype is referring to the scores from the head branch of this pipeline, while "_will" suffix is the scores from @wsdewitt 's prototype (currently being used in the replay pipeline), and "_topic" are the scores being reported from the refactored pipeline, here. 

Screenshot from 2024-11-08 11-53-43
Screenshot from 2024-11-08 11-53-21

## Major Code Changes

* Improved [TiteSeq modeling](https://github.com/jbloomlab/Ab-CGGnaive_DMS/pull/13/files?file-filters%5B%5D=.Rmd&file-filters%5B%5D=.bash&file-filters%5B%5D=.ipynb&file-filters%5B%5D=.md&file-filters%5B%5D=.yaml&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-3e20d8a62715054fcea2d1d29137b5dfd0d532534d3c486215704307e4548e5a) has been implemented
* TuGG data, and related processing code has been removed
* Logic, and a [parameter flag](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/7ee70a7b89d197d8166d71bb4765ac0e1dfd17ed/config.yaml#L5) for running the CSS, and variant count steps has been added so the workflow can be run without NGS data.
* PSR calculation has been completely removed from the workflow
* The pipeline now collapses barcodes before computing both Binding, and Expression, and updates all downstream analysis to comply with the new data
* Created reproducible environments for all rules
* Sane logging has been added to the steps for cleaner stdout when running the pipeline
* Slashed a good bit from the [README](https://github.com/jbloomlab/Ab-CGGnaive_DMS/pull/13/files?file-filters%5B%5D=.Rmd&file-filters%5B%5D=.bash&file-filters%5B%5D=.ipynb&file-filters%5B%5D=.md&file-filters%5B%5D=.yaml&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), and re-wrote instructions to run the pipeline given the new setup
* Removed un-tracked files from [.gitattributes](https://github.com/jbloomlab/Ab-CGGnaive_DMS/pull/13/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393e)
* changed the [.gitignore](https://github.com/jbloomlab/Ab-CGGnaive_DMS/pull/13/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) to simply include the unwanted (?) intermediate pipeline output files 
* Updated the configuration yaml file to include new parameters for filtering steps, new files, removed old files etc

**Review by wsdewitt — COMMENTED** [review]
Amazing work, @jgallowa07! This looks about ready to me, but let's have @tylernstarr review and approve the PR before merging (I can't approve because I'm a PR author). The only minor thing I noticed is that the math isn't rendered in the ipynb -> md conversion (but I'm not too worried, since it will still be there in the ipynb).

**Comment by tylernstarr** [comment]
Awesome, I'll take a more detailed look as well in the next day or two -- but quick question for Jared or Will is -- do you know what mutation corresponds to the one point that falls off the 1:1 line for the bind_CGG_will versus _topic scatterplot? (And secondarily, why it might be getting a different score in this build)

**Comment by tylernstarr** [comment]
Everything else looks good, with the remaining question about that one point falling off the line

**Comment by jgallowa07** [comment]
Yea, so that is the mutation `Y52(H)R`. The comparison notebook [found here](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/tite-seq-modeling/compare_fvs.ipynb) shows a delta of 0.314. Given the aggregated WT variant being fed into the optimizer has changed (since we dropped synonymous mutants from in the [prep-stage](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/results/summary/normalize_filter_aggregate_barcodes.md#filter-synonymous-variants-with-silent-mutations), where we were not doing so in [will's notebook](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/tite-seq-modeling/tite-seq-modeling.ipynb)), It's not surprising to me that the there;s a delta here. I did, however, plot the sigmoids for this mutation by suggestion of @wsdewitt - They look ok to me?

Screenshot from 2024-11-19 15-12-00
Screenshot from 2024-11-19 15-11-52

**Comment by jgallowa07** [comment]
Thanks for your review, @tylernstarr !

Could I get your thoughts on point number three above:

> There's some sort of bug with how we're recording the link mutations in the final variants table. For example, there's only 13 wildtype linker sites reported, and there should be 15 according to the site map. I don't really see any benefit to keeping these in the final variant table. The only entries with non-NA phenotype values are just reporting the wildtype value ... the rest just have confusing IMGT mutations, and cause the table to have a weird number of entries when sanity checking. See the notebook for more.

Given every single analysis of this data has a line of code saying "chain != 'link'" - I'm wondering if we should just cut these from the final_variants_table.csv ? I'm agnostic but there are bugs there somewhere within [collapse_scores.Rmd](https://github.com/jbloomlab/Ab-CGGnaive_DMS/blob/improved-Kd-fitting/collapse_scores.Rmd)

Almost there!

**Comment by wsdewitt** [comment]
Thanks @jgallowa07! I agree, the fit for Y47R looks reasonable, or at least not totally pathological (it's not perfect, but seems to be in the typical range of non-perfection).

I'm not sure why the final variants table is missing some linker sites, but is it possible the sites that appear in this table are based on the sites that were seen as mutated, and it just so happens we have no mutations for some linker sites? @tylernstarr, let us know if there's something obvious here we might be missing.

**Comment by tylernstarr** [comment]
Yep, linker mutations are just sort of side-products, not what is actually engineered into the libraries but they happen. It's important to propagate them for a bit since they *are* in the expeirment and so need to make it into the part where read counts are normalized by cell counts -- otherwise their contribution to cell counts but lack of presence in the read counts (if excluding these barcodes when doing original variant calling) would be problematic. So, they stuck around for a bit but I didn't bother doing much with them, but as you say they get excluded from plotting since we don't actually care about them. And as Will says, they're sporadically there because some sites and linker muts just didn't happen so I didn't bother building them in.

**Comment by jgallowa07** [comment]
Awesome - sounds like:
1. we're happy with the Y47R fit, and
2. we should leave the linker sites as they are. 

I'm going to go ahead and remove the experimental files, squash, and merge by EOD unless there's anything else y'all want me to look into.

**Comment by wsdewitt** [comment]
I'm good with that—thanks!

**Comment by matsen** [comment]
🎉 🎉 🎉 thank you @jgallowa07 !

**Pull request merged**
